### ISSUE TITLE
Error: Cannot get access token for Azure Cost Management API

### ISSUE THREAD

**Issue by lalekov** [vuder/AzureCostAnomalyDetector#17]
Thank you with help with parameters earlier, but no I have issue with access token. Error is below:
`[Error] Executed 'AzureCostAnomalyDetector' (Failed, Id=*** Duration=95ms)Cannot get access token for Azure Cost Management API. Error: {"error":"invalid_client","error_description":"AADSTS7000216: 'client_assertion', 'client_secret' or 'request' is required for the 'client_credentials' grant type.\r\nTrace ID: ***\r\nCorrelation ID: ***\r\nTimestamp: 2021-07-30 07:22:03Z","error_codes":[7000216],"timestamp":"2021-07-30 07:22:03Z","trace_id":"***","correlation_id":"***","error_uri":"https://login.microsoftonline.com/error?code=7000216"}`

My guess is that I didn't give necessary permissions.
Can you please explain what permissions I need to give? 
And are AzureAppRegistrationClientId and AzureAppRegistrationClientSecret used in case that I don't run function localy?

**Comment by vuder** [comment]
looks like the function cannot access cost management api
in order to provide the access you should do follwing:
 - create App Registration in Azure AD
 - Add Web Platform configuration with any redirect URI
 - Add API permissions for Azure Service Management 
 - Generate Client Secret 
Once it is done you will have app registration that have access to cost management api and it can be used to get access tokens that provide access to the api

then use Application ID and generated client secret as a configuration parameters of the Function:
AzureCostAnomalyDetector.AzureAppRegistrationClientId
AzureCostAnomalyDetector.AzureAppRegistrationClientSecret

**Comment by lalekov** [comment]
Great, I will test it out. Thank you for help.

Just a quick question about scope of data: when I run this function, does it collect and analyze cost data for subscription or for whole tenant?

**Comment by vuder** [comment]
current implementation works in single subscription scope.
If you need to run analysis on multiple subscriptions you should either update code of the function or  run it multiple times with different subscription id configuration parameter

**Comment by lalekov** [comment]
Great, thanks for tip!
